/**
 * Demo seed — populates the database so the app shows meaningful data on first
 * load without any GitHub calls or token. It reuses the DAL upsert paths, so it
 * is idempotent: re-running overwrites the same rows by stable githubId and
 * leaves the user↔repo links untouched.
 *
 * Run with `pnpm seed`. Values are plausible static snapshots, not live data;
 * `pnpm dev` + a refresh replaces them with current GitHub data once a token is
 * configured.
 */
import 'dotenv/config';
import { ensureDemoUser } from '../src/dal/users.js';
import { findRepoByOwnerName, linkUserRepo, upsertRepo } from '../src/dal/repos.js';
import { disconnectPrisma } from '../src/prisma.js';
import type { LanguageDto } from '../src/dto/index.js';

/** A repo to seed plus the watermark that decides its seen/unseen state. */
interface SeedRepo {
  githubId: number;
  owner: string;
  name: string;
  description: string;
  url: string;
  authorUrl: string;
  avatarUrl: string;
  stars: number;
  watchers: number;
  forks: number;
  languages: LanguageDto[];
  latestReleaseVersion: string | null;
  latestReleasePublishedAt: string | null;
  latestReleaseUrl: string | null;
  /**
   * The version the demo user last acknowledged. When it trails
   * latestReleaseVersion the repo shows as unseen; equal (or no release) is seen.
   */
  lastSeenReleaseVersion: string;
}

/**
 * Thirty-nine well-known repos with static, plausible snapshots — enough to
 * span more than one page so pagination is exercised on first load. A mix carry
 * a watermark behind their latest release (rendered unseen, driving the toolbar
 * count); the rest are caught up. All use real GitHub ids, so the background
 * sync refreshes them in place rather than creating duplicates.
 *
 * `lastSeenReleaseVersion: ''` means nothing acknowledged yet -> unseen; a value
 * equal to `latestReleaseVersion` means seen.
 */
const SEED_REPOS: readonly SeedRepo[] = [
  {
    githubId: 10270250,
    owner: 'react',
    name: 'react',
    description:
      'The library for web and native user interfaces.',
    url: 'https://github.com/react/react',
    authorUrl: 'https://github.com/react',
    avatarUrl: 'https://avatars.githubusercontent.com/u/69631?v=4',
    stars: 228000,
    watchers: 6500,
    forks: 46600,
    languages: [
      { name: 'JavaScript', color: '#f1e05a' },
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'HTML', color: '#e34c26' },
    ],
    latestReleaseVersion: 'v19.1.0',
    latestReleasePublishedAt: '2025-03-28T00:00:00.000Z',
    latestReleaseUrl: 'https://github.com/facebook/react/releases/tag/v19.1.0',
    // Behind latest -> unseen.
    lastSeenReleaseVersion: 'v19.0.0',
  },
  {
    githubId: 41881900,
    owner: 'microsoft',
    name: 'vscode',
    description:
      'Visual Studio Code — open-source code editor from Microsoft.',
    url: 'https://github.com/microsoft/vscode',
    authorUrl: 'https://github.com/microsoft',
    avatarUrl: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    stars: 164000,
    watchers: 3300,
    forks: 29000,
    languages: [
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'JavaScript', color: '#f1e05a' },
      { name: 'CSS', color: '#563d7c' },
    ],
    latestReleaseVersion: '1.99.3',
    latestReleasePublishedAt: '2025-04-14T00:00:00.000Z',
    latestReleaseUrl: 'https://github.com/microsoft/vscode/releases/tag/1.99.3',
    // Behind latest -> unseen.
    lastSeenReleaseVersion: '1.98.2',
  },
  {
    githubId: 27193779,
    owner: 'nodejs',
    name: 'node',
    description: 'Node.js JavaScript runtime built on V8.',
    url: 'https://github.com/nodejs/node',
    authorUrl: 'https://github.com/nodejs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/9950313?v=4',
    stars: 109000,
    watchers: 2900,
    forks: 30500,
    languages: [
      { name: 'JavaScript', color: '#f1e05a' },
      { name: 'C++', color: '#f34b7d' },
      { name: 'Python', color: '#3572A5' },
    ],
    latestReleaseVersion: 'v24.0.0',
    latestReleasePublishedAt: '2025-05-06T00:00:00.000Z',
    latestReleaseUrl: 'https://github.com/nodejs/node/releases/tag/v24.0.0',
    // Behind latest -> unseen.
    lastSeenReleaseVersion: 'v23.11.0',
  },
  {
    githubId: 174214770,
    owner: 'prisma',
    name: 'prisma',
    description:
      'Next-generation ORM for Node.js & TypeScript.',
    url: 'https://github.com/prisma/prisma',
    authorUrl: 'https://github.com/prisma',
    avatarUrl: 'https://avatars.githubusercontent.com/u/17219288?v=4',
    stars: 40000,
    watchers: 280,
    forks: 1600,
    languages: [
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'Rust', color: '#dea584' },
      { name: 'JavaScript', color: '#f1e05a' },
    ],
    latestReleaseVersion: '6.6.0',
    latestReleasePublishedAt: '2025-04-08T00:00:00.000Z',
    latestReleaseUrl: 'https://github.com/prisma/prisma/releases/tag/6.6.0',
    // Equal to latest -> seen.
    lastSeenReleaseVersion: '6.6.0',
  },
  {
    githubId: 70107786,
    owner: 'vercel',
    name: 'next.js',
    description: 'The React Framework for the Web.',
    url: 'https://github.com/vercel/next.js',
    authorUrl: 'https://github.com/vercel',
    avatarUrl: 'https://avatars.githubusercontent.com/u/14985020?v=4',
    stars: 132000,
    watchers: 1500,
    forks: 28200,
    languages: [
      { name: 'JavaScript', color: '#f1e05a' },
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'Rust', color: '#dea584' },
    ],
    latestReleaseVersion: 'v15.3.1',
    latestReleasePublishedAt: '2025-04-17T00:00:00.000Z',
    latestReleaseUrl: 'https://github.com/vercel/next.js/releases/tag/v15.3.1',
    // Equal to latest -> seen.
    lastSeenReleaseVersion: 'v15.3.1',
  },
  {
    githubId: 257485422,
    owner: 'vitejs',
    name: 'vite',
    description: 'Next generation frontend tooling — it\'s fast!',
    url: 'https://github.com/vitejs/vite',
    authorUrl: 'https://github.com/vitejs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/65625612?v=4',
    stars: 81354,
    watchers: 537,
    forks: 8287,
    languages: [
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'JavaScript', color: '#f1e05a' },
      { name: 'HTML', color: '#e34c26' },
    ],
    latestReleaseVersion: 'v8.0.16',
    latestReleasePublishedAt: '2026-06-01T09:50:08.000Z',
    latestReleaseUrl: 'https://github.com/vitejs/vite/releases/tag/v8.0.16',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 106017343,
    owner: 'tailwindlabs',
    name: 'tailwindcss',
    description: 'A utility-first CSS framework for rapid UI development.',
    url: 'https://github.com/tailwindlabs/tailwindcss',
    authorUrl: 'https://github.com/tailwindlabs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/67109815?v=4',
    stars: 95463,
    watchers: 765,
    forks: 5294,
    languages: [
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'CSS', color: '#563d7c' },
      { name: 'JavaScript', color: '#f1e05a' },
    ],
    latestReleaseVersion: 'v4.3.0',
    latestReleasePublishedAt: '2026-05-08T20:17:25.000Z',
    latestReleaseUrl: 'https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.3.0',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 133442384,
    owner: 'denoland',
    name: 'deno',
    description: 'A modern runtime for JavaScript and TypeScript.',
    url: 'https://github.com/denoland/deno',
    authorUrl: 'https://github.com/denoland',
    avatarUrl: 'https://avatars.githubusercontent.com/u/42048915?v=4',
    stars: 107009,
    watchers: 1410,
    forks: 6064,
    languages: [
      { name: 'Rust', color: '#dea584' },
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'JavaScript', color: '#f1e05a' },
    ],
    latestReleaseVersion: 'v2.8.2',
    latestReleasePublishedAt: '2026-06-03T13:41:42.000Z',
    latestReleaseUrl: 'https://github.com/denoland/deno/releases/tag/v2.8.2',
    lastSeenReleaseVersion: 'v2.8.2',
  },
  {
    githubId: 74293321,
    owner: 'sveltejs',
    name: 'svelte',
    description: 'Web development for the rest of us.',
    url: 'https://github.com/sveltejs/svelte',
    authorUrl: 'https://github.com/sveltejs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/23617963?v=4',
    stars: 87165,
    watchers: 946,
    forks: 4941,
    languages: [
      { name: 'JavaScript', color: '#f1e05a' },
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'HTML', color: '#e34c26' },
    ],
    latestReleaseVersion: 'svelte@5.56.3',
    latestReleasePublishedAt: '2026-06-07T18:30:29.000Z',
    latestReleaseUrl: 'https://github.com/sveltejs/svelte/releases/tag/svelte%405.56.3',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 348060227,
    owner: 'withastro',
    name: 'astro',
    description: 'The web framework for content-driven websites.',
    url: 'https://github.com/withastro/astro',
    authorUrl: 'https://github.com/withastro',
    avatarUrl: 'https://avatars.githubusercontent.com/u/44914786?v=4',
    stars: 59969,
    watchers: 210,
    forks: 3524,
    languages: [
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'JavaScript', color: '#f1e05a' },
      { name: 'CSS', color: '#563d7c' },
    ],
    latestReleaseVersion: 'astro@6.4.5',
    latestReleasePublishedAt: '2026-06-09T12:46:16.000Z',
    latestReleaseUrl: 'https://github.com/withastro/astro/releases/tag/astro%406.4.5',
    lastSeenReleaseVersion: 'astro@6.4.5',
  },
  {
    githubId: 214587193,
    owner: 'supabase',
    name: 'supabase',
    description: 'The Postgres development platform.',
    url: 'https://github.com/supabase/supabase',
    authorUrl: 'https://github.com/supabase',
    avatarUrl: 'https://avatars.githubusercontent.com/u/54469796?v=4',
    stars: 103919,
    watchers: 768,
    forks: 12689,
    languages: [
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'JavaScript', color: '#f1e05a' },
      { name: 'CSS', color: '#563d7c' },
    ],
    latestReleaseVersion: 'v1.26.05',
    latestReleasePublishedAt: '2026-05-07T23:45:42.000Z',
    latestReleaseUrl: 'https://github.com/supabase/supabase/releases/tag/v1.26.05',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 658928958,
    owner: 'ollama',
    name: 'ollama',
    description: 'Get up and running with large language models locally.',
    url: 'https://github.com/ollama/ollama',
    authorUrl: 'https://github.com/ollama',
    avatarUrl: 'https://avatars.githubusercontent.com/u/151674099?v=4',
    stars: 173704,
    watchers: 983,
    forks: 16524,
    languages: [
      { name: 'Go', color: '#00ADD8' },
      { name: 'C', color: '#555555' },
      { name: 'Shell', color: '#89e051' },
    ],
    latestReleaseVersion: 'v0.30.7',
    latestReleasePublishedAt: '2026-06-07T21:51:48.000Z',
    latestReleaseUrl: 'https://github.com/ollama/ollama/releases/tag/v0.30.7',
    lastSeenReleaseVersion: 'v0.30.7',
  },
  {
    githubId: 15111821,
    owner: 'grafana',
    name: 'grafana',
    description:
      'The open and composable observability and data visualization platform.',
    url: 'https://github.com/grafana/grafana',
    authorUrl: 'https://github.com/grafana',
    avatarUrl: 'https://avatars.githubusercontent.com/u/7195757?v=4',
    stars: 74314,
    watchers: 1260,
    forks: 14040,
    languages: [
      { name: 'TypeScript', color: '#3178c6' },
      { name: 'Go', color: '#00ADD8' },
      { name: 'JavaScript', color: '#f1e05a' },
    ],
    latestReleaseVersion: 'v13.0.2',
    latestReleasePublishedAt: '2026-06-09T11:19:16.000Z',
    latestReleaseUrl: 'https://github.com/grafana/grafana/releases/tag/v13.0.2',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 17728164,
    owner: 'hashicorp',
    name: 'terraform',
    description:
      'Safely and predictably create, change, and improve infrastructure as code.',
    url: 'https://github.com/hashicorp/terraform',
    authorUrl: 'https://github.com/hashicorp',
    avatarUrl: 'https://avatars.githubusercontent.com/u/761456?v=4',
    stars: 48623,
    watchers: 1150,
    forks: 10364,
    languages: [
      { name: 'Go', color: '#00ADD8' },
      { name: 'Shell', color: '#89e051' },
      { name: 'HTML', color: '#e34c26' },
    ],
    latestReleaseVersion: 'v1.15.5',
    latestReleasePublishedAt: '2026-05-27T14:52:52.000Z',
    latestReleaseUrl: 'https://github.com/hashicorp/terraform/releases/tag/v1.15.5',
    lastSeenReleaseVersion: 'v1.15.5',
  },
  {
    githubId: 11180687,
    owner: 'gohugoio',
    name: 'hugo',
    description: 'The world\'s fastest framework for building websites.',
    url: 'https://github.com/gohugoio/hugo',
    authorUrl: 'https://github.com/gohugoio',
    avatarUrl: 'https://avatars.githubusercontent.com/u/29385237?v=4',
    stars: 88491,
    watchers: 1078,
    forks: 8268,
    languages: [
      { name: 'Go', color: '#00ADD8' },
      { name: 'HTML', color: '#e34c26' },
      { name: 'JavaScript', color: '#f1e05a' },
    ],
    latestReleaseVersion: 'v0.163.0',
    latestReleasePublishedAt: '2026-06-08T14:36:18.000Z',
    latestReleaseUrl: 'https://github.com/gohugoio/hugo/releases/tag/v0.163.0',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 1103012935,
    owner: 'openclaw',
    name: 'openclaw',
    description: 'Your own personal AI assistant. Any OS. Any Platform. The lobster way. 🦞',
    url: 'https://github.com/openclaw/openclaw',
    authorUrl: 'https://github.com/openclaw',
    avatarUrl: 'https://avatars.githubusercontent.com/u/252820863?v=4',
    stars: 377828,
    watchers: 6000,
    forks: 79000,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v2026.6.5',
    latestReleasePublishedAt: '2026-06-09T18:13:20.000Z',
    latestReleaseUrl: 'https://github.com/openclaw/openclaw/releases/tag/v2026.6.5',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 11730342,
    owner: 'vuejs',
    name: 'vue',
    description: 'This is the repo for Vue 2. For Vue 3, go to https://github.com/vuejs/core',
    url: 'https://github.com/vuejs/vue',
    authorUrl: 'https://github.com/vuejs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/6128107?v=4',
    stars: 209836,
    watchers: 4663,
    forks: 33717,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v2.7.16',
    latestReleasePublishedAt: '2023-12-24T15:02:39.000Z',
    latestReleaseUrl: 'https://github.com/vuejs/vue/releases/tag/v2.7.16',
    lastSeenReleaseVersion: 'v2.7.16',
  },
  {
    githubId: 193215554,
    owner: 'n8n-io',
    name: 'n8n',
    description: 'Fair-code workflow automation platform with native AI capabilities. Combine visual building with cus',
    url: 'https://github.com/n8n-io/n8n',
    authorUrl: 'https://github.com/n8n-io',
    avatarUrl: 'https://avatars.githubusercontent.com/u/45487711?v=4',
    stars: 191792,
    watchers: 4262,
    forks: 58422,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'n8n@2.25.6',
    latestReleasePublishedAt: '2026-06-08T10:56:56.000Z',
    latestReleaseUrl: 'https://github.com/n8n-io/n8n/releases/tag/n8n%402.25.6',
    lastSeenReleaseVersion: 'n8n@2.25.6',
  },
  {
    githubId: 975734319,
    owner: 'anomalyco',
    name: 'opencode',
    description: 'The open source coding agent.',
    url: 'https://github.com/anomalyco/opencode',
    authorUrl: 'https://github.com/anomalyco',
    avatarUrl: 'https://avatars.githubusercontent.com/u/66570915?v=4',
    stars: 172127,
    watchers: 3825,
    forks: 20642,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v1.16.2',
    latestReleasePublishedAt: '2026-06-05T15:58:51.000Z',
    latestReleaseUrl: 'https://github.com/anomalyco/opencode/releases/tag/v1.16.2',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 626805178,
    owner: 'langgenius',
    name: 'dify',
    description: 'Production-ready platform for agentic workflow development.',
    url: 'https://github.com/langgenius/dify',
    authorUrl: 'https://github.com/langgenius',
    avatarUrl: 'https://avatars.githubusercontent.com/u/127165244?v=4',
    stars: 144580,
    watchers: 3213,
    forks: 22750,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: '1.14.2',
    latestReleasePublishedAt: '2026-05-19T05:34:25.000Z',
    latestReleaseUrl: 'https://github.com/langgenius/dify/releases/tag/1.14.2',
    lastSeenReleaseVersion: '1.14.2',
  },
  {
    githubId: 787076358,
    owner: 'firecrawl',
    name: 'firecrawl',
    description: 'The API to search, scrape, and interact with the web at scale. 🔥',
    url: 'https://github.com/firecrawl/firecrawl',
    authorUrl: 'https://github.com/firecrawl',
    avatarUrl: 'https://avatars.githubusercontent.com/u/135057108?v=4',
    stars: 130708,
    watchers: 2905,
    forks: 7734,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v2.10',
    latestReleasePublishedAt: '2026-05-15T17:34:45.000Z',
    latestReleaseUrl: 'https://github.com/firecrawl/firecrawl/releases/tag/v2.10',
    lastSeenReleaseVersion: 'v2.10',
  },
  {
    githubId: 231283452,
    owner: 'excalidraw',
    name: 'excalidraw',
    description: 'Virtual whiteboard for sketching hand-drawn like diagrams',
    url: 'https://github.com/excalidraw/excalidraw',
    authorUrl: 'https://github.com/excalidraw',
    avatarUrl: 'https://avatars.githubusercontent.com/u/59452120?v=4',
    stars: 124969,
    watchers: 2777,
    forks: 13971,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v0.18.1',
    latestReleasePublishedAt: '2026-04-21T08:43:20.000Z',
    latestReleaseUrl: 'https://github.com/excalidraw/excalidraw/releases/tag/v0.18.1',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 721767116,
    owner: 'clash-verge-rev',
    name: 'clash-verge-rev',
    description: 'A modern GUI client based on Tauri, designed to run in Windows, macOS and Linux for tailored proxy e',
    url: 'https://github.com/clash-verge-rev/clash-verge-rev',
    authorUrl: 'https://github.com/clash-verge-rev',
    avatarUrl: 'https://avatars.githubusercontent.com/u/152534467?v=4',
    stars: 124404,
    watchers: 2765,
    forks: 9057,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v2.5.1',
    latestReleasePublishedAt: '2026-05-20T07:01:22.000Z',
    latestReleaseUrl: 'https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v2.5.1',
    lastSeenReleaseVersion: 'v2.5.1',
  },
  {
    githubId: 157616880,
    owner: 'iptv-org',
    name: 'iptv',
    description: 'Collection of publicly available IPTV channels from all over the world',
    url: 'https://github.com/iptv-org/iptv',
    authorUrl: 'https://github.com/iptv-org',
    avatarUrl: 'https://avatars.githubusercontent.com/u/55937028?v=4',
    stars: 117494,
    watchers: 2611,
    forks: 6250,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 585146387,
    owner: 'shadcn-ui',
    name: 'ui',
    description: 'A set of beautifully-designed, accessible components and a code distribution platform. Works with yo',
    url: 'https://github.com/shadcn-ui/ui',
    authorUrl: 'https://github.com/shadcn-ui',
    avatarUrl: 'https://avatars.githubusercontent.com/u/139895814?v=4',
    stars: 116088,
    watchers: 2580,
    forks: 9015,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'shadcn@4.11.0',
    latestReleasePublishedAt: '2026-06-08T13:49:39.000Z',
    latestReleaseUrl: 'https://github.com/shadcn-ui/ui/releases/tag/shadcn%404.11.0',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 20929025,
    owner: 'microsoft',
    name: 'TypeScript',
    description: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript output.',
    url: 'https://github.com/microsoft/TypeScript',
    authorUrl: 'https://github.com/microsoft',
    avatarUrl: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    stars: 109169,
    watchers: 2426,
    forks: 13424,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v6.0.3',
    latestReleasePublishedAt: '2026-04-16T23:43:08.000Z',
    latestReleaseUrl: 'https://github.com/microsoft/TypeScript/releases/tag/v6.0.3',
    lastSeenReleaseVersion: 'v6.0.3',
  },
  {
    githubId: 1179264259,
    owner: 'garrytan',
    name: 'gstack',
    description: 'Use Garry Tan\'s exact Claude Code setup: 23 opinionated tools that serve as CEO, Designer, Eng Mana',
    url: 'https://github.com/garrytan/gstack',
    authorUrl: 'https://github.com/garrytan',
    avatarUrl: 'https://avatars.githubusercontent.com/u/19957?v=4',
    stars: 108666,
    watchers: 2415,
    forks: 16163,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 968197216,
    owner: 'google-gemini',
    name: 'gemini-cli',
    description: 'An open-source AI agent that brings the power of Gemini directly into your terminal.',
    url: 'https://github.com/google-gemini/gemini-cli',
    authorUrl: 'https://github.com/google-gemini',
    avatarUrl: 'https://avatars.githubusercontent.com/u/161781182?v=4',
    stars: 105097,
    watchers: 2335,
    forks: 14021,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v0.45.2',
    latestReleasePublishedAt: '2026-06-05T20:15:25.000Z',
    latestReleaseUrl: 'https://github.com/google-gemini/gemini-cli/releases/tag/v0.45.2',
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 455229168,
    owner: 'immich-app',
    name: 'immich',
    description: 'High performance self-hosted photo and video management solution.',
    url: 'https://github.com/immich-app/immich',
    authorUrl: 'https://github.com/immich-app',
    avatarUrl: 'https://avatars.githubusercontent.com/u/109746326?v=4',
    stars: 102936,
    watchers: 2287,
    forks: 5798,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v2.7.5',
    latestReleasePublishedAt: '2026-04-13T14:53:55.000Z',
    latestReleaseUrl: 'https://github.com/immich-app/immich/releases/tag/v2.7.5',
    lastSeenReleaseVersion: 'v2.7.5',
  },
  {
    githubId: 24195339,
    owner: 'angular',
    name: 'angular',
    description: 'Deliver web apps with confidence 🚀',
    url: 'https://github.com/angular/angular',
    authorUrl: 'https://github.com/angular',
    avatarUrl: 'https://avatars.githubusercontent.com/u/139426?v=4',
    stars: 100301,
    watchers: 2229,
    forks: 27174,
    languages: [{ name: 'TypeScript', color: '#3178c6' }],
    latestReleaseVersion: 'v22.0.0',
    latestReleasePublishedAt: '2026-06-03T13:03:46.000Z',
    latestReleaseUrl: 'https://github.com/angular/angular/releases/tag/v22.0.0',
    lastSeenReleaseVersion: 'v22.0.0',
  },
  {
    githubId: 23096959,
    owner: 'golang',
    name: 'go',
    description: 'The Go programming language',
    url: 'https://github.com/golang/go',
    authorUrl: 'https://github.com/golang',
    avatarUrl: 'https://avatars.githubusercontent.com/u/4314092?v=4',
    stars: 134632,
    watchers: 2992,
    forks: 18988,
    languages: [{ name: 'Go', color: '#00ADD8' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 20580498,
    owner: 'kubernetes',
    name: 'kubernetes',
    description: 'Production-Grade Container Scheduling and Management',
    url: 'https://github.com/kubernetes/kubernetes',
    authorUrl: 'https://github.com/kubernetes',
    avatarUrl: 'https://avatars.githubusercontent.com/u/13629408?v=4',
    stars: 122896,
    watchers: 2731,
    forks: 43176,
    languages: [{ name: 'Go', color: '#00ADD8' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 48378947,
    owner: 'fatedier',
    name: 'frp',
    description: 'A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.',
    url: 'https://github.com/fatedier/frp',
    authorUrl: 'https://github.com/fatedier',
    avatarUrl: 'https://avatars.githubusercontent.com/u/7346661?v=4',
    stars: 107211,
    watchers: 2382,
    forks: 15059,
    languages: [{ name: 'Go', color: '#00ADD8' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 20904437,
    owner: 'gin-gonic',
    name: 'gin',
    description: 'Gin is a high-performance HTTP web framework written in Go. It provides a Martini-like API but with ',
    url: 'https://github.com/gin-gonic/gin',
    authorUrl: 'https://github.com/gin-gonic',
    avatarUrl: 'https://avatars.githubusercontent.com/u/7894478?v=4',
    stars: 88656,
    watchers: 1970,
    forks: 8629,
    languages: [{ name: 'Go', color: '#00ADD8' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 14712850,
    owner: 'syncthing',
    name: 'syncthing',
    description: 'Open Source Continuous File Synchronization',
    url: 'https://github.com/syncthing/syncthing',
    authorUrl: 'https://github.com/syncthing',
    avatarUrl: 'https://avatars.githubusercontent.com/u/7628018?v=4',
    stars: 85175,
    watchers: 1893,
    forks: 5260,
    languages: [{ name: 'Go', color: '#00ADD8' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 13807606,
    owner: 'junegunn',
    name: 'fzf',
    description: ':cherry_blossom: A command-line fuzzy finder',
    url: 'https://github.com/junegunn/fzf',
    authorUrl: 'https://github.com/junegunn',
    avatarUrl: 'https://avatars.githubusercontent.com/u/700826?v=4',
    stars: 80960,
    watchers: 1799,
    forks: 2793,
    languages: [{ name: 'Go', color: '#00ADD8' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 134017286,
    owner: 'jesseduffield',
    name: 'lazygit',
    description: 'simple terminal UI for git commands',
    url: 'https://github.com/jesseduffield/lazygit',
    authorUrl: 'https://github.com/jesseduffield',
    avatarUrl: 'https://avatars.githubusercontent.com/u/8456633?v=4',
    stars: 79177,
    watchers: 1759,
    forks: 2856,
    languages: [{ name: 'Go', color: '#00ADD8' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 29207621,
    owner: 'caddyserver',
    name: 'caddy',
    description: 'Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS',
    url: 'https://github.com/caddyserver/caddy',
    authorUrl: 'https://github.com/caddyserver',
    avatarUrl: 'https://avatars.githubusercontent.com/u/12955528?v=4',
    stars: 73298,
    watchers: 1629,
    forks: 4770,
    languages: [{ name: 'Go', color: '#00ADD8' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
  {
    githubId: 7691631,
    owner: 'moby',
    name: 'moby',
    description: 'The Moby Project - a collaborative project for the container ecosystem to assemble container-based s',
    url: 'https://github.com/moby/moby',
    authorUrl: 'https://github.com/moby',
    avatarUrl: 'https://avatars.githubusercontent.com/u/27259197?v=4',
    stars: 71643,
    watchers: 1592,
    forks: 18959,
    languages: [{ name: 'Go', color: '#00ADD8' }],
    latestReleaseVersion: null,
    latestReleasePublishedAt: null,
    latestReleaseUrl: null,
    lastSeenReleaseVersion: '',
  },
];

/** Upsert one seed repo and link it to the demo user at its watermark. */
const seedRepo = async (
  userId: string,
  spec: SeedRepo,
  syncedAt: Date,
): Promise<boolean> => {
  await upsertRepo({
    githubId: spec.githubId,
    owner: spec.owner,
    name: spec.name,
    description: spec.description,
    url: spec.url,
    authorUrl: spec.authorUrl,
    avatarUrl: spec.avatarUrl,
    stars: spec.stars,
    watchers: spec.watchers,
    forks: spec.forks,
    languages: spec.languages,
    latestReleaseVersion: spec.latestReleaseVersion,
    latestReleasePublishedAt: spec.latestReleasePublishedAt
      ? new Date(spec.latestReleasePublishedAt)
      : null,
    latestReleaseUrl: spec.latestReleaseUrl,
    lastSyncedAt: syncedAt,
    lastSyncStatus: 'SUCCESS',
  });
  // upsertRepo keys on githubId; re-read by owner/name to resolve the UUID id
  // the link needs.
  const repo = await findRepoByOwnerName(spec.owner, spec.name);
  if (!repo) {
    throw new Error(`seed: repo ${spec.owner}/${spec.name} not found after upsert`);
  }
  // linkUserRepo is a no-op update when the edge already exists, so the
  // watermark survives re-seeding (and any later markSeen) unchanged.
  await linkUserRepo(userId, repo.id, spec.lastSeenReleaseVersion);
  return (
    spec.latestReleaseVersion !== null &&
    spec.latestReleaseVersion !== spec.lastSeenReleaseVersion
  );
};

const main = async (): Promise<void> => {
  const user = await ensureDemoUser();
  let unseen = 0;
  let index = 0;
  const DAY_MS = 24 * 60 * 60 * 1000;
  for (const spec of SEED_REPOS) {
    // Vary lastSyncedAt so the sync-freshness dot shows a spread of states:
    // most fresh (green), some > 1 week (yellow), a few > 1 month (red).
    const daysAgo = index % 8 === 3 ? 45 : index % 4 === 1 ? 12 : 0;
    const syncedAt = new Date(Date.now() - daysAgo * DAY_MS);
    // eslint-disable-next-line no-await-in-loop
    const isUnseen = await seedRepo(user.id, spec, syncedAt);
    if (isUnseen) {
      unseen += 1;
    }
    index += 1;
  }
  // eslint-disable-next-line no-console
  console.log(
    `Seeded ${SEED_REPOS.length} repos for user "${user.handle}" ` +
      `(${unseen} unseen, ${SEED_REPOS.length - unseen} seen).`,
  );
};

main()
  .catch((error: unknown) => {
    // eslint-disable-next-line no-console
    console.error('Seed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await disconnectPrisma();
  });
